version: '3.7'

services:
  dayone:
    image: rtl
    build: ./
    environment:
      NODE_ENV: production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: "db"
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    tty: true
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}